### ISSUE TITLE
macOS下release的程序如何启动

### ISSUE THREAD

**Issue by GrooveSino** [werifu/keyboard-heatmap#5]
[keyboard-heatmap-aarch64-apple](https://github.com/werifu/keyboard-heatmap/releases/download/v0.1.0/keyboard-heatmap-aarch64-apple)

这个文件该如何启动，没有任何格式

**Comment by werifu** [comment]
omg, 好像是 mac 的安全策略使得陌生的编译成二进制的文件不能打开。发布release的时候没有考虑到这点，目前mac用户只能源码编译了，即在项目目录下执行 cargo build --release，我本周争取申请个mac的开发者身份，可以发行带签名的app版本。不便见谅

**Comment by GrooveSino** [comment]
麻烦作者了。

**Comment by GrooveWJH** [comment]
> 麻烦作者了。 使用`cargo run`可以启动
